config/routes.rb
Rails.application.routes.draw do
  resources :shortened_urls do
    get "check_shorten_url", on: :collection
    get "expand", on: :collection
    get "convert", on: :collection
  
  end

   root 'shortened_urls#check_shorten_url'
   get '*key' => "shortened_urls#convert"

end

app/models/shortened_url.rb
class ShortenedUrl < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :set_shortened_url, only: [:show, :edit, :update, :destroy]
  # GET /shortened_urls
  # GET /shortened_urls.json
  def index
    @shortened_urls = ShortenedUrl.all
  end

  # GET /shortened_urls/1
  # GET /shortened_urls/1.json
  def show
  end

  # GET /shortened_urls/new
  def new
    @shortened_url = ShortenedUrl.new
  end

  # GET /shortened_urls/1/edit
  def edit
  end

  # POST /shortened_urls
  # POST /shortened_urls.json
  def create
    @shortened_url = ShortenedUrl.new(shortened_url_params)

    respond_to do |format|
      if @shortened_url.save
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @shortened_url }
      else
        format.html { render :new }
        format.js
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

def convert
#   shorten = UrlShortener::Client.shorten(params[:url]) 
   shorten = true
   if params[:url]
     @shortened_url = ShortenedUrl.where(url: params[:url]).first
   else
     @shortened_url = ShortenedUrl.where(unique_key: params[:key]).first
   end
   if !@shortened_url.present? and params[:url]
      shorten = UrlShortener::Client.shorten(params[:url])
      @shortened_url= ShortenedUrl.create(unique_key:  shorten,:url => params[:url])  if shorten    
   end
      @display_url =  shorten ? UrlShortener::Client.generate_shorten_url(@shortened_url.unique_key) : "Url already Short"
      @shortened_url.new_record? ? @display_url : "You will be redirected .."
   respond_to do |format|
        format.js
        format.html { redirect_to @shortened_url.url, notice: 'Shortened url was successfully created.' }
        format.json { render :show, status: :created, attr: @shortened_url,:shorten => @display_url }
    end
 
end

def expand
    original_url = ShortenedUrl.where(unique_key: params[:url]).first
    if original_url
       @display_url = original_url.url
   else
     @display_url = "No Match Found"
    end

    respond_to do |format|
        format.html { redirect_to  shortened_urls_path ,notice: 'Original url was successfully created.' }
        format.js
        format.json { render :show, status: :created,:original_url => original_url.url }
    end
end

def check_shorten_url
 
 end

  # PATCH/PUT /shortened_urls/1
  # PATCH/PUT /shortened_urls/1.json
  def update
    respond_to do |format|
      if @shortened_url.update(shortened_url_params)
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortened_url }
      else
        format.html { render :edit }
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortened_urls/1
  # DELETE /shortened_urls/1.json
  def destroy
    @shortened_url.destroy
    respond_to do |format|
      format.html { redirect_to shortened_urls_url, notice: 'Shortened url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortened_url
      @shortened_url = ShortenedUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortened_url_params
      params[:shortened_url]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_for @shortened_url, :html => { :class => "form-horizontal shortened_url" } do |f| %>

    <% if @shortened_url.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shortened_url.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :owner_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :owner_id, :class => 'form-control' %>
    </div>
    <%= error_span(@shortened_url[:owner_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :owner_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :owner_type, :class => 'form-control' %>
    </div>
    <%= error_span(@shortened_url[:owner_type]) %>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= error_span(@shortened_url[:url]) %>
  </div>
  <div class="control-group">
    <%= f.label :unique_key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unique_key, :class => 'form-control' %>
    </div>
    <%= error_span(@shortened_url[:unique_key]) %>
  </div>
  <div class="control-group">
    <%= f.label :expires_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :expires_at, :class => 'form-control' %>
    </div>
    <%= error_span(@shortened_url[:expires_at]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            shortened_urls_path, :class => 'btn btn-default' %>

<% end %>

app/views/shortened_urls/check_shorten_url.html.erb
<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 side hidden-sm">

<div class="container-fluid span well">
						<div class="row-fluid">
							<div class="span9">
								
								<div class="page-header">
  <h1>Verify URLs</h1>
</div>  
<form action="/shortened_urls/convert" class="button_to" data-remote="true" method="get">
<div class="input-group">
     <span class="input-group-btn">
        <input type="submit" class="btn btn-primary" value="Convert To Shorten<" name="commit">
        <!-- <button class="btn btn-primary" type="button">Convert To Shorten</button> --!>
      </span>
      <%= text_field_tag :url,nil, :class => 'form-control', :placeholder => "Please Enter Your URL",:required => true %>
  </div>
</form>
<br/>
<form action="/shortened_urls/expand" class="button_to" data-remote="true" method="get">
  <div class="input-group">
      <span class="input-group-btn">
        <input type="submit" class="btn btn-primary" value="Convert To Original" name="commit">
      </span>
      <%= text_field_tag :url,nil, :class => 'form-control',:placeholder => "Please Enter Your Shorten URL",:required => true %>
  </div>
</form>
</div>
<div>
<div>
<div>
<div>
<br/>
<div class="result">
</div>
<a href="/shortened_urls" class="btn btn-primary">All Links</a>

app/views/shortened_urls/convert.js.erb
$('.result').html('<p class="short_url">Result: <%= link_to @display_url, @display_url, target: "_blank" %></p>')

app/views/shortened_urls/edit.html.erb
<%- model_class = ShortenedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shortened_urls/expand.js.erb
$('.result').html('<p class="short_url">Result: <%= link_to @display_url, @display_url, target: "_blank" %></p>')

app/views/shortened_urls/index.html.erb
<%- model_class = ShortenedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:owner_id) %></th>
      <th><%= model_class.human_attribute_name(:owner_type) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:unique_key) %></th>
      <th><%= model_class.human_attribute_name(:expires_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shortened_urls.each do |shortened_url| %>
      <tr>
        <td><%= link_to shortened_url.id, shortened_url_path(shortened_url) %></td>
        <td><%= shortened_url.owner_id %></td>
        <td><%= shortened_url.owner_type %></td>
        <td><%= shortened_url.url %></td>
        <td><%= shortened_url.unique_key %></td>
        <td><%= shortened_url.expires_at %></td>
        <td><%=l shortened_url.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shortened_url_path(shortened_url), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shortened_url_path(shortened_url),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shortened_url_path,
            :class => 'btn btn-primary' %>

app/views/shortened_urls/new.html.erb
<%- model_class = ShortenedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shortened_urls/show.html.erb
<%- model_class = ShortenedUrl -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:owner_id) %>:</strong></dt>
  <dd><%= @shortened_url.owner_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner_type) %>:</strong></dt>
  <dd><%= @shortened_url.owner_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @shortened_url.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unique_key) %>:</strong></dt>
  <dd><%= @shortened_url.unique_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expires_at) %>:</strong></dt>
  <dd><%= @shortened_url.expires_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shortened_urls_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shortened_url_path(@shortened_url), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shortened_url_path(@shortened_url),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>